# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

2) Создать нулевой вектор размера 10

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [5]:
a = np.full(7, 7, dtype = int)
a

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [8]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [10]:
a = np.random.random(5)
a[::-1]

array([0.16323831, 0.26180995, 0.0130139 , 0.53358721, 0.09524883])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [12]:
np.arange(0, 9, 1).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [13]:
np.diag(np.ones(4), 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [17]:
np.full((4, 4), 7, dtype=int) + np.diag(np.arange(1, 5) - 7)

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [20]:
np.zeros((5, 5)) + np.arange(0, 5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [19]:
a = np.random.random((10, 10))
a - a.mean(axis = 1)[:,np.newaxis]

array([[ 0.02049358,  0.34685174, -0.30006116,  0.31978559, -0.1393878 ,
         0.28045044, -0.26184384, -0.45173979, -0.1586034 ,  0.34405463],
       [ 0.29551868, -0.17246769, -0.01560412,  0.36602399, -0.40762895,
         0.22444655,  0.04838003, -0.33818004,  0.29126511, -0.29175357],
       [ 0.1960109 ,  0.2360854 , -0.36785365,  0.38623838,  0.0070781 ,
         0.09795898, -0.34771685,  0.25283916, -0.04496041, -0.41568002],
       [-0.11756255, -0.42818259,  0.36909893,  0.24835046,  0.09772652,
         0.29301015, -0.26850323, -0.3109195 ,  0.06115425,  0.05582757],
       [-0.24786948,  0.29841862,  0.42660429,  0.17154166, -0.31761401,
        -0.20829832, -0.16854515, -0.01558685,  0.12515625, -0.06380702],
       [ 0.3477855 ,  0.20627382, -0.24433893, -0.04395886,  0.35775077,
        -0.28054165, -0.23275336,  0.09016499, -0.19574515, -0.00463713],
       [-0.15354828,  0.11790634,  0.50780768, -0.41050082, -0.20835176,
         0.0483309 ,  0.12926035,  0.06816701

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [23]:
a = np.random.random((10, 10))
a - np.median(a, axis = 0)

array([[-0.23371307, -0.01190102,  0.02185059, -0.18636267, -0.10992471,
         0.0337606 ,  0.03116542,  0.15997692, -0.24663286, -0.46587205],
       [-0.35964017, -0.20299729,  0.47712225, -0.21676028,  0.10992471,
         0.49837777, -0.03116542,  0.05407346,  0.13748437, -0.34822054],
       [-0.19798465,  0.01190102, -0.20304354,  0.55927989, -0.22432055,
         0.00400495, -0.30064975,  0.35172475,  0.13129063,  0.21696406],
       [ 0.28044018, -0.45060381,  0.4123912 ,  0.10083259,  0.4679159 ,
        -0.11730618,  0.27576272, -0.05407346,  0.21879558, -0.13772717],
       [ 0.47868944,  0.29674108, -0.02185059,  0.36048184, -0.16272283,
        -0.05664401, -0.15193484, -0.09215621, -0.04874094,  0.28443692],
       [-0.04759122, -0.43694531,  0.1816922 ,  0.60535602,  0.22399069,
        -0.00400495, -0.29697463, -0.18953689, -0.03093757,  0.17414681],
       [ 0.56895838,  0.11456851,  0.35671853, -0.20916917,  0.40883058,
        -0.10259208,  0.34249181, -0.30191791

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [31]:
a = np.random.random((5, 5))
b = a.min(axis = 1)[:,np.newaxis]
c = a.max(axis = 1)[:,np.newaxis]
np.hstack((a, b, c))

array([[0.16249197, 0.63097923, 0.67853191, 0.08558772, 0.15760611,
        0.08558772, 0.67853191],
       [0.1783659 , 0.17865559, 0.42863657, 0.31131773, 0.49592782,
        0.1783659 , 0.49592782],
       [0.65466601, 0.99281892, 0.7946584 , 0.79990195, 0.5852565 ,
        0.5852565 , 0.99281892],
       [0.58988498, 0.95657373, 0.18424635, 0.26876387, 0.62547972,
        0.18424635, 0.95657373],
       [0.56283535, 0.60666413, 0.97149812, 0.38613819, 0.74779002,
        0.38613819, 0.97149812]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [45]:
a = np.arange(1, 51)
nechet = a[::2]
chet = a[1::2]

np.linalg.inv(nechet.reshape((5,5)) @ chet.reshape((5,5)))

LinAlgError: ignored

**Обратной матрицы не существует**

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [33]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
